### ISSUE TITLE
Unable to access the provided Google Drive link without permission

### ISSUE THREAD

**Issue by yachenkang** [tgangwani/RL-Indirect-imitation#2]
As the title says, I need to obtain permission when accessing the google drive link used to download expert trjectory, which is the data necessary to run the code. How can I obtain the permission or get the expert trjectory data through my own training? Thanks!

**Comment by tgangwani** [comment]
Hi, could you please tell me the email address with which you logged into Google drive and requested the permissions?

**Comment by yachenkang** [comment]
OK，the email address is sherlock-bear@outlook.com

**Comment by tgangwani** [comment]
Can you access the folder now?

**Comment by yachenkang** [comment]
Yep, thanks very much!
